version: '3'
services:
  traefik:
    restart: always
    image: traefik:v2.0
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports: 
      # Http, https
      - "80:80"
      - "443:443"
    volumes:
      # Chemin vers le fichier de configuration, fichier de certificats,accès Docker, et localtime de l'hôte
      - "./data/traefik.yml:/traefik.yml:ro"
      - "./data/acme.json:/acme.json"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/etc/localtime:/etc/localtime:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=it-anthony:$$apr1$$jEtBeIN8$$MhbywMULOmeDzi8M9op8J0"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=http"
      - "traefik.http.routers.traefik-secure.service=api@internal"
  web-01:
    restart: always
    image: httpd
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web-01.rule=Host(`web-01.localhost`)"  
      - "traefik.http.routers.web-01.entrypoints=http"
networks:
    proxy:
      external: true
